spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sb-all
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create # create-每次创建表，同时数据会丢失；update-根据model
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      temp:
        use_jdbc_metadata_defaults: true
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    addresses: 192.168.3.17
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true
---
spring:
  profiles: prod
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sb-all
    username: postgres
    password: 123456
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    addresses: 192.168.3.17
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true